version: '3.8'

x-aws-vpc: ${AWS_VPC}
x-aws-cluster: ${AWS_ECS_CLUSTER}
x-aws-loadbalancer: ${AWS_ELB}


## Production docker-compose
services:
  client:
    build: ./web-scrape-client
    container_name: scraper-client
    image: lefantan/scraper-client
    expose:
      - 3000
  api:
    build: ./WebScrapeApi
    container_name: scraper-api
    image: lefantan/scraper-api
    expose:
      - 5000
  server:
    build: ./nginx
    container_name: scraper-server
    ports:
      - "443:443"

